service: bridge
handlers:
  - url: /_app/immutable/
    static_dir: storage/_app/immutable
    expiration: 30d 0h
  - url: /_app/
    static_dir: storage/_app
    http_headers:
      Access-Control-Allow-Origin: '*'
  - url: /.*
    secure: always
    script: auto
