// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	meta: {
		/**
		 * MVM Bridge
		 */
		title: string
		/**
		 * The best cross-chain bridge.
		 */
		description: string
		keywords: {
			/**
			 * Cross-Chain Bridge
			 */
			crossChainBridge: string
			/**
			 * Bitcoin
			 */
			bitcoin: string
			/**
			 * Bridge
			 */
			bridge: string
			/**
			 * Ethereum Bridge
			 */
			ethereumBridge: string
			/**
			 * MobileCoin MetaMask
			 */
			mobileCoinMetaMask: string
		}
	}
	error: {
		/**
		 * Error
		 */
		tips: string
	}
	/**
	 * Assets
	 */
	assets: string
	/**
	 * Transactions
	 */
	transactions: string
	/**
	 * Swap
	 */
	swap: string
	/**
	 * Explorer
	 */
	explorer: string
	/**
	 * Audit
	 */
	audit: string
	logout: {
		/**
		 * Log Out
		 */
		title: string
		/**
		 * Are you sure want to logout?
		 */
		description: string
	}
	/**
	 * Yes
	 */
	yes: string
	/**
	 * Cancel
	 */
	cancel: string
	/**
	 * Deposit
	 */
	deposit: string
	/**
	 * Withdraw
	 */
	withdraw: string
	searchBar: {
		/**
		 * Search
		 */
		title: string
		/**
		 * Name, Symbol or Address
		 */
		placeholder: string
	}
	depositModal: {
		/**
		 * Deposit to MVM
		 */
		title: string
		/**
		 * QR Code
		 */
		qrCode: string
		/**
		 * Deposit will arrive {0} block confirmation.
		 * @param {number} 0
		 */
		tips1: RequiredParams<'0'>
		/**
		 * Min deposit: 0.00000001 {0}.
		 * @param {string} 0
		 */
		tips2: RequiredParams<'0'>
	}
	withdrawModal: {
		/**
		 * Withdrawal fee: {0} {1}
		 * @param {string} 0
		 * @param {string} 1
		 */
		tips1: RequiredParams<'0' | '1'>
		/**
		 * Gas fee: {0} ETH
		 * @param {unknown} 0
		 */
		tips2: RequiredParams<'0'>
	}
	/**
	 * From
	 */
	from: string
	/**
	 * To
	 */
	to: string
	/**
	 * Address
	 */
	address: string
	/**
	 * Memo
	 */
	memo: string
	/**
	 * All Transactions
	 */
	allTransactions: string
	/**
	 * Fee
	 */
	fee: string
	/**
	 * Balance: {0} {1}
	 * @param {string} 0
	 * @param {string} 1
	 */
	balanceOf: RequiredParams<'0' | '1'>
	swapPage: {
		tips: {
			/**
			 * Price:
			 */
			price: string
			/**
			 * Min Received:
			 */
			minReceived: string
			/**
			 * Fee:
			 */
			fee: string
			/**
			 * Price Impact:
			 */
			priceImpact: string
			/**
			 * Lack of liquidity, please decrease swap amount
			 */
			warning: string
		}
		faq: {
			/**
			 * How does it work?
			 */
			description1: string
			/**
			 * MVM Bridge provides a cross-chain convert service through 4swap and MixPay, which delivers lower fees, faster transaction speed, and better trading liquidity.
			 */
			description2: string
			/**
			 * 4swap
			 */
			description3: string
			/**
			 * A decentralized protocol for automated liquidity provision offers over 140 pairs with a TVL of over $100M. Please visit 
			 */
			description4: string
			/**
			 *  for additional information.
			 */
			description5: string
			/**
			 * MixPay
			 */
			description6: string
			/**
			 * A decentralized Web3 payment protocol connects the most liquid exchanges, such as Binance, Huobi, and Gate, to convert almost any cryptocurrency. For more info, please visit 
			 */
			description7: string
			/**
			 * .
			 */
			description8: string
		}
	}
	login: {
		/**
		 * Login
		 */
		title: string
		/**
		 * Connect using browser wallet
		 */
		connectBrowserWalletDescription: string
		/**
		 * Connect using WalletConnect
		 */
		connectWalletConnectDescription: string
	}
}

export type TranslationFunctions = {
	meta: {
		/**
		 * MVM Bridge
		 */
		title: () => LocalizedString
		/**
		 * The best cross-chain bridge.
		 */
		description: () => LocalizedString
		keywords: {
			/**
			 * Cross-Chain Bridge
			 */
			crossChainBridge: () => LocalizedString
			/**
			 * Bitcoin
			 */
			bitcoin: () => LocalizedString
			/**
			 * Bridge
			 */
			bridge: () => LocalizedString
			/**
			 * Ethereum Bridge
			 */
			ethereumBridge: () => LocalizedString
			/**
			 * MobileCoin MetaMask
			 */
			mobileCoinMetaMask: () => LocalizedString
		}
	}
	error: {
		/**
		 * Error
		 */
		tips: () => LocalizedString
	}
	/**
	 * Assets
	 */
	assets: () => LocalizedString
	/**
	 * Transactions
	 */
	transactions: () => LocalizedString
	/**
	 * Swap
	 */
	swap: () => LocalizedString
	/**
	 * Explorer
	 */
	explorer: () => LocalizedString
	/**
	 * Audit
	 */
	audit: () => LocalizedString
	logout: {
		/**
		 * Log Out
		 */
		title: () => LocalizedString
		/**
		 * Are you sure want to logout?
		 */
		description: () => LocalizedString
	}
	/**
	 * Yes
	 */
	yes: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Deposit
	 */
	deposit: () => LocalizedString
	/**
	 * Withdraw
	 */
	withdraw: () => LocalizedString
	searchBar: {
		/**
		 * Search
		 */
		title: () => LocalizedString
		/**
		 * Name, Symbol or Address
		 */
		placeholder: () => LocalizedString
	}
	depositModal: {
		/**
		 * Deposit to MVM
		 */
		title: () => LocalizedString
		/**
		 * QR Code
		 */
		qrCode: () => LocalizedString
		/**
		 * Deposit will arrive {0} block confirmation.
		 */
		tips1: (arg0: number) => LocalizedString
		/**
		 * Min deposit: 0.00000001 {0}.
		 */
		tips2: (arg0: string) => LocalizedString
	}
	withdrawModal: {
		/**
		 * Withdrawal fee: {0} {1}
		 */
		tips1: (arg0: string, arg1: string) => LocalizedString
		/**
		 * Gas fee: {0} ETH
		 */
		tips2: (arg0: unknown) => LocalizedString
	}
	/**
	 * From
	 */
	from: () => LocalizedString
	/**
	 * To
	 */
	to: () => LocalizedString
	/**
	 * Address
	 */
	address: () => LocalizedString
	/**
	 * Memo
	 */
	memo: () => LocalizedString
	/**
	 * All Transactions
	 */
	allTransactions: () => LocalizedString
	/**
	 * Fee
	 */
	fee: () => LocalizedString
	/**
	 * Balance: {0} {1}
	 */
	balanceOf: (arg0: string, arg1: string) => LocalizedString
	swapPage: {
		tips: {
			/**
			 * Price:
			 */
			price: () => LocalizedString
			/**
			 * Min Received:
			 */
			minReceived: () => LocalizedString
			/**
			 * Fee:
			 */
			fee: () => LocalizedString
			/**
			 * Price Impact:
			 */
			priceImpact: () => LocalizedString
			/**
			 * Lack of liquidity, please decrease swap amount
			 */
			warning: () => LocalizedString
		}
		faq: {
			/**
			 * How does it work?
			 */
			description1: () => LocalizedString
			/**
			 * MVM Bridge provides a cross-chain convert service through 4swap and MixPay, which delivers lower fees, faster transaction speed, and better trading liquidity.
			 */
			description2: () => LocalizedString
			/**
			 * 4swap
			 */
			description3: () => LocalizedString
			/**
			 * A decentralized protocol for automated liquidity provision offers over 140 pairs with a TVL of over $100M. Please visit 
			 */
			description4: () => LocalizedString
			/**
			 *  for additional information.
			 */
			description5: () => LocalizedString
			/**
			 * MixPay
			 */
			description6: () => LocalizedString
			/**
			 * A decentralized Web3 payment protocol connects the most liquid exchanges, such as Binance, Huobi, and Gate, to convert almost any cryptocurrency. For more info, please visit 
			 */
			description7: () => LocalizedString
			/**
			 * .
			 */
			description8: () => LocalizedString
		}
	}
	login: {
		/**
		 * Login
		 */
		title: () => LocalizedString
		/**
		 * Connect using browser wallet
		 */
		connectBrowserWalletDescription: () => LocalizedString
		/**
		 * Connect using WalletConnect
		 */
		connectWalletConnectDescription: () => LocalizedString
	}
}

export type Formatters = {}
